HOME = os.getenv("HOME")

require("vim_settings")
require("post_write")
require("plugins")
require("key_bindings")
require("style")
require("telescope_config")
require("lsp")
require("completion")
require("dap_config")
